language: elixir

elixir: 1.10.4

otp_release: 23.0

services:
  - postgresql

env:
  - MIX_ENV=test

addons:
  postgresql: "11.2"

before_install:
  - rm -rf ~/.mix/ ; mix local.hex --force ; mix local.rebar --force
  - mix deps.get
  - cp config/travis.exs config/test.exs
  - mix do ecto.create, ecto.migrate
